### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by iamericanartist**
pushing up progress, need to fix "undefined" in js/models.js

### CODE REVIEW

**Comment by morecallan** [comment]
I always love reviewing your submissions (all 2 times). Very well commented and organized, which is a great marketable skill for development. You've got a good start on your prototypal inheritance; I can tell you are getting it down. Because, it's very important to your skill set as a developer, always consider the following when thinking about your prototypal chain:
1. If you are repeating any functionality, try moving your functionality a level (or levels) up and let your chained elements inherit it.
2. Each step in the chain (here, it is robot, types, models) should provide _meaning_ to the chain, re: it has useful methods and properties that factor in later.

Looks like you've already got a great start. Let me know if you want a sounding board  for any ideas.

**Comment by iamericanartist** [comment]
So you're saying I can merge this? 🤓

**Comment by morecallan** [comment]
@iamericanartist only 1+ years later.

**Comment by iamericanartist** [comment]
OH SWEEEEEET 💯 👍  ;) 
@morecallan

**Pull request merged**
